# sea potential api worker
name = "sea-potential-api"
main = "index.js"
compatibility_date = "2026-03-18"

[[kv_namespaces]]
binding = "SP_STORE"
# TODO: replace this placeholder with your real namespace ID after running:
#   npx wrangler kv namespace create SP_STORE
id = "0cd28269c6da43bc9e43db1687efc221"
